apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: salievak
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: salievak-chart
      version: ">=0.2.0"  # або конкретна версія
      sourceRef:
        kind: HelmRepository
        name: salievak-chart
        namespace: flux-system

