apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: salievak-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/salievak/helm-charts.git
    targetRevision: main
    path: argocd/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

