apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: salievak-app
  namespace: argocd
spec:
 project: default
 source:
   repoURL: ghcr.io/salievak/helm-charts
   targetRevision: 0.2.0
   chart: salievak-chart
 destination:
   server: https://kubernetes.default.svc
   namespace: default
 syncPolicy:
   automated: {}
