apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: 3000
