name: Build and Publish OCI Helm Chart

on:
  push:
    paths:
      - 'salievak-chart/**'   # Слідкуємо лише за змінами у папці чарта
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Helm Lint
        run: helm lint ./salievak-chart

      - name: Package Helm Chart
        run: helm package ./salievak-chart --destination packaged-chart

      - name: Login to OCI Registry
        run: helm registry login ghcr.io --username ${{ secrets.GHCR_USERNAME }} --password ${{ secrets.GHCR_TOKEN }}

      - name: Publish Chart to OCI Registry
        run: |
          CHART_PACKAGE=$(ls packaged-chart/*.tgz)
          helm push "$CHART_PACKAGE" oci://ghcr.io/salievak/helm-charts/salievak-chart

