name: Publish Helm Chart
on:
  push:
    branches: [ main ]
    tags: [ '*' ]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Chart
        run: |
          helm lint helm-chart
          helm package helm-chart \
            --version ${GITHUB_SHA::8} \
            --destination .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Chart to OCI Registry
        run: |
          helm push salievak-chart-${GITHUB_SHA::8}.tgz oci://ghcr.io/salievak/helm-charts
          echo "CHART_VERSION=${GITHUB_SHA::8}" >> $GITHUB_ENV
