name: Publish Helm Chart

on:
  push:
    branches:
      - main  # Гілка, з якої запускається pipeline
    paths:
      - 'helm-charts/**'  # Шлях до вашого чарту

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v0.2.1

      - name: Configure OCI Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u salievak --password-stdin

      - name: Package and Push Chart
        run: |
          helm dependency update helm-charts
          helm package helm-charts -d ./dist
          helm push ./dist/salievak-chart-*.tgz oci://ghcr.io/salievak/helm-charts
